---

- name: Install OpenJDK
  become: yes
  apt:
    name: openjdk-7-jre-headless

- name: Ensure install folders
  become: yes
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ kafka.user }}"
    group: "{{ kafka.group }}"
  with_items:
    - "/home/{{ kafka.user }}/tmp"
    - "/home/{{ kafka.user }}/log"
    - "/home/{{ kafka.user }}/data"

- name: Remove lost+found in the datadir
  become: yes
  file:
    path: "/home/{{ kafka.user }}/data/lost+found"
    state: absent

- name: Fetch kafka binary package
  become: yes
  get_url:
    dest: "/home/{{ kafka.user }}/tmp/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"
    url: "{{ kafka.apache_mirror }}/kafka/{{ kafka.version_kafka }}/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"

- name: Uncompress the kafka tar
  become: yes
  unarchive:
    copy: no
    creates: "/home/{{ kafka.user }}/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}"
    dest: "/home/{{ kafka.user }}"
    src: "/home/{{ kafka.user }}/tmp/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}.tgz"
    owner: "{{ kafka.user }}"
    group: "{{ kafka.group }}"

- name: Link kafka to the right version
  become: yes
  file:
    path: "/home/{{ kafka.user }}/kafka"
    src: "/home/{{ kafka.user }}/kafka_{{ kafka.version_scala }}-{{ kafka.version_kafka }}"
    state: link
    owner: "{{ kafka.user }}"
    group: "{{ kafka.group }}"

- name: link config dir
  become: yes
  file:
    force: yes
    path: "/home/{{ kafka.user }}/etc"
    src: "/home/{{ kafka.user }}/kafka/config"
    state: link
    owner: "{{ kafka.user }}"
    group: "{{ kafka.group }}"
