---

# Needed to ensure some services start properly
- name: Set hostname
  become: yes
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 {{ ansible_hostname }}"
  notify:
    - restart kafka

- name: Overwrite the start script so the Java Opts can be changed if Kafka 0.8.1.1
  become: yes
  lineinfile:
    dest: "/opt/kafka_2.9.2-{{ kafka.version_kafka }}/bin/kafka-server-start.sh"
    regexp: "^export KAFKA_HEAP_OPTS="
    line: "export KAFKA_HEAP_OPTS=\"{{ kafka.heap_opts }}\""
  notify:
    - restart kafka
  when: kafka.version_kafka == "0.8.1.1"

- name: Create upstart config
  become: yes
  template:
    dest: "{{ kafka.upstart_conf }}"
    owner: root
    group: root
    mode: 0644
    src: kafka.conf.j2
  notify:
    - restart kafka
  when: not kafka.use_systemd

- name: Create systemd config
  become: yes
  template:
    dest: "{{ kafka.systemd_service }}"
    owner: root
    group: root
    mode: 0644
    src: kafka.service.j2
  notify:
    - restart kafka
  when: kafka.use_systemd

- name: Reload systemd
  become: yes
  command: systemctl daemon-reload
  when: kafka.use_systemd

- name: Create log4j.properties
  become: yes
  template:
    dest: "/home/{{ kafka.user }}/etc/log4j.properties"
    mode: 0644
    src: log4j.properties.j2
    owner: "{{ kafka.user }}"
    group: "{{ kafka.user }}"
  notify:
    - restart kafka

- name: Create server.properties
  become: yes
  template:
    dest: "/home/{{ kafka.user }}/etc/server.properties"
    mode: 0640
    src: server.properties.j2
    owner: "{{ kafka.user }}"
    group: "{{ kafka.user }}"
  notify:
    - restart kafka

- name: Ensure Kafka is running
  become: yes
  service:
    name: kafka
    state: started
    enabled: yes

- name: Wait for Kafka port
  wait_for:
    port: "{{ kafka.port }}"
    state: started
    timeout: 30
